export const colorsConfig = {
  primary: {
    50: "rgb(var(--primary-50) / <alpha-value>)",
    100: "rgb(var(--primary-100) / <alpha-value>)",
    200: "rgb(var(--primary-200) / <alpha-value>)",
    300: "rgb(var(--primary-300) / <alpha-value>)",
    400: "rgb(var(--primary-400) / <alpha-value>)",
    500: "rgb(var(--primary-500) / <alpha-value>)",
    600: "rgb(var(--primary-600) / <alpha-value>)",
    700: "rgb(var(--primary-700) / <alpha-value>)",
    800: "rgb(var(--primary-800) / <alpha-value>)",
    900: "rgb(var(--primary-900) / <alpha-value>)",
  },
  secondary: {
    50: "rgb(var(--secondary-50) / <alpha-value>)",
    100: "rgb(var(--secondary-100) / <alpha-value>)",
    200: "rgb(var(--secondary-200) / <alpha-value>)",
    300: "rgb(var(--secondary-300) / <alpha-value>)",
    400: "rgb(var(--secondary-400) / <alpha-value>)",
    500: "rgb(var(--secondary-500) / <alpha-value>)",
    600: "rgb(var(--secondary-600) / <alpha-value>)",
  },
  text: {
    main: "rgb(var(--text-main) / <alpha-value>)",
    second: "rgb(var(--text-second) / <alpha-value>)",
    third: "rgb(var(--text-third) / <alpha-value>)",
    fourth: "rgb(var(--text-fourth) / <alpha-value>)",
  },
  bg: {
    main: "rgb(var(--bg-main) / <alpha-value>)",
    second: "rgb(var(--bg-second) / <alpha-value>)",
    third: "rgb(var(--bg-third) / <alpha-value>)",
    fourth: "rgb(var(--bg-fourth) / <alpha-value>)",
    fifth: "rgb(var(--bg-fifth) / <alpha-value>)",
    sixth: "rgb(var(--bg-sixth) / <alpha-value>)",
    seventh: "rgb(var(--bg-seventh) / <alpha-value>)",
    eighth: "rgb(var(--bg-eighth) / <alpha-value>)",
    ninth: "rgb(var(--bg-ninth) / <alpha-value>)",
    tenth: "rgb(var(--bg-tenth) / <alpha-value>)",
    overlay: "var(--bg-overlay)",
    modal: "var(--bg-modal)",
    glass: "var(--bg-glass)",
    card: "rgb(var(--bg-card) / <alpha-value>)",
    sidebar: "rgb(var(--bg-sidebar) / <alpha-value>)",
    header: "rgb(var(--bg-header) / <alpha-value>)",
    footer: "rgb(var(--bg-footer) / <alpha-value>)",
    hover: "rgb(var(--bg-hover) / <alpha-value>)",
    active: "rgb(var(--bg-active) / <alpha-value>)",
    disabled: "rgb(var(--bg-disabled) / <alpha-value>)",
  },
  btn: {
    main: "rgb(var(--btn-main) / <alpha-value>)",
    second: "rgb(var(--btn-second) / <alpha-value>)",
    third: "rgb(var(--btn-third) / <alpha-value>)",
    fourth: "rgb(var(--btn-fourth) / <alpha-value>)",
  },
  border: {
    main: "rgb(var(--border-main) / <alpha-value>)",
    second: "rgb(var(--border-second) / <alpha-value>)",
    focus: "rgb(var(--border-focus) / <alpha-value>)",
  },
  gradient: {
    main: "var(--gradient-main)",
    second: "var(--gradient-second)",
  },
  success: "rgb(var(--success) / <alpha-value>)",
  warning: "rgb(var(--warning) / <alpha-value>)",
  error: "rgb(var(--error) / <alpha-value>)",
  info: "rgb(var(--info) / <alpha-value>)",
};
