export const themeDetails = [
  {
    key: "default",
    label: "Mặc định",
    isDefault: true,
  },
  {
    key: "chat-emerald",
    label: "Emerald",
    light: {
      gradient: "bg-gradient-to-tr from-[#107a51] to-[#85e3ad]",
      primaryLight: "#85e3ad",
      primaryMain: "#107a51",
      bgMain: "#f0f8f5",
      bgSecond: "#d7f0e4",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#0f766e] to-[#34d399]",
      primaryLight: "#34d399",
      primaryMain: "#10b981",
      bgMain: "#0a1812",
      bgSecond: "#0f2019",
    },
  },
  {
    key: "chat-sunset",
    label: "Sunset",
    light: {
      gradient: "bg-gradient-to-tr from-[#f26c4f] to-[#ffd700]",
      primaryLight: "#ffd700",
      primaryMain: "#f26c4f",
      bgMain: "#fff8f3",
      bgSecond: "#ffe4d2",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#9a3412] to-[#f97316]",
      primaryLight: "#f97316",
      primaryMain: "#ea580c",
      bgMain: "#18100c",
      bgSecond: "#201611",
    },
  },
  {
    key: "chat-cyberpunk",
    label: "Cyberpunk",
    light: {
      gradient: "bg-gradient-to-tr from-[#db2777] to-[#06b6d4]",
      primaryLight: "#06b6d4",
      primaryMain: "#db2777",
      bgMain: "#fdf4ff",
      bgSecond: "#f5e5fa",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#ff007f] to-[#00f2fe]",
      primaryLight: "#00f2fe",
      primaryMain: "#ff007f",
      bgMain: "#12101a",
      bgSecond: "#191624",
    },
  },
  {
    key: "chat-lavender",
    label: "Lavender",
    light: {
      gradient: "bg-gradient-to-tr from-[#7255de] to-[#c4b5fd]",
      primaryLight: "#c4b5fd",
      primaryMain: "#7255de",
      bgMain: "#f8f6fe",
      bgSecond: "#e6e0f8",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#6d28d9] to-[#c4b5fd]",
      primaryLight: "#c4b5fd",
      primaryMain: "#8b5cf6",
      bgMain: "#0f0d16",
      bgSecond: "#15121e",
    },
  },
  {
    key: "chat-ocean",
    label: "Ocean Deep",
    light: {
      gradient: "bg-gradient-to-tr from-[#0e74b5] to-[#90e0ef]",
      primaryLight: "#90e0ef",
      primaryMain: "#0e74b5",
      bgMain: "#f2f8fc",
      bgSecond: "#d7ebf8",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#0369a1] to-[#38bdf8]",
      primaryLight: "#38bdf8",
      primaryMain: "#0284c7",
      bgMain: "#08121a",
      bgSecond: "#0c1a26",
    },
  },
  {
    key: "chat-bubblegum",
    label: "Bubblegum",
    light: {
      gradient: "bg-gradient-to-tr from-[#ec4887] to-[#fbcfe8]",
      primaryLight: "#fbcfe8",
      primaryMain: "#ec4887",
      bgMain: "#fef6f8",
      bgSecond: "#f9dce6",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#be185d] to-[#f472b6]",
      primaryLight: "#f472b6",
      primaryMain: "#db2777",
      bgMain: "#180c12",
      bgSecond: "#221018",
    },
  },
  {
    key: "chat-worldcup",
    label: "World Cup",
    isEvent: true,
    light: {
      gradient: "bg-gradient-to-tr from-[#15803d] to-[#4ade80]",
      primaryLight: "#4ade80",
      primaryMain: "#15803d",
      bgMain: "#f0f8f5",
      bgSecond: "#d7f0e4",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#166534] to-[#22c55e]",
      primaryLight: "#22c55e",
      primaryMain: "#15803d",
      bgMain: "#0a1812",
      bgSecond: "#0f2019",
    },
  },
  {
    key: "chat-vietnam",
    label: "Việt Nam",
    isEvent: true,
    light: {
      gradient: "bg-gradient-to-tr from-[#da251d] to-[#ffcd00]",
      primaryLight: "#ffcd00",
      primaryMain: "#da251d",
      bgMain: "#fef2f2",
      bgSecond: "#fee2e2",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#991b1b] to-[#ffcd00]",
      primaryLight: "#ffcd00",
      primaryMain: "#da251d",
      bgMain: "#180a0a",
      bgSecond: "#240f0f",
    },
  },
  {
    key: "chat-vutru",
    label: "Vũ trụ",
    light: {
      gradient: "bg-gradient-to-tr from-[#6366f1] to-[#ec4899]",
      primaryLight: "#ec4899",
      primaryMain: "#8b5cf6",
      bgMain: "#f5f3ff",
      bgSecond: "#ede9fe",
    },
    dark: {
      gradient: "bg-gradient-to-tr from-[#312e81] to-[#831843]",
      primaryLight: "#831843",
      primaryMain: "#4c1d95",
      bgMain: "#0a0718",
      bgSecond: "#100c24",
    },
  },
];
